version: 1
console_log:
  level: INFO
formatters:
  simple:
    class: logging.Formatter
    format: "%(asctime)s %(name)s %(levelname)s: %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S"
handlers:
  file:
    class: logging.FileHandler
    filename: train.log
    level: DEBUG
    formatter: simple
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: DEBUG
    formatter: simple
loggers:
  train:
    level: DEBUG
    handlers: [file, console]
root:
  handlers: []

