apiVersion: v1
kind: Pod
metadata:
  name: online-inference
spec:
  containers:
    - name: ml-serivce
      image: holyketzer/made-ml-inference
      imagePullPolicy: Always
      ports:
        - name: api
          containerPort: 8000
          protocol: TCP
      resources:
        requests:
          memory: "100Mi"
          cpu: "0.5"
        limits:
          memory: "200Mi"
          cpu: "1"
      livenessProbe:
        httpGet:
          path: /live_check
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /ready_check
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 10
