apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference
  labels:
    name: online-inference
spec:
  replicas: 3
  selector:
    matchLabels:
      name: online-inference
  template:
    metadata:
      labels:
        name: online-inference
    spec:
      containers:
        - name: ml-serivce
          image: holyketzer/made-ml-inference
          ports:
            - name: api
              containerPort: 8000
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.5"
            limits:
              memory: "200Mi"
              cpu: "1"
